# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our issue template. Please resubmit with the correct template."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Empire Version"
  - "Starkiller Version"
  - "OS Information (Linux flavor, Python version)"
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Screenshots"
  - "Additional context"

- content:
# Example 2: feature request
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd like"
  - "Describe alternatives you've considered"
  - "Additional context"
  
- content:
# Example 3: fall back
  - "Empire Version"
  - "OS Information (Linux flavor, Python version)"
  - "Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better."
  - "Screenshot of error, embedded text output, or Pastebin link to the error"
  - "Any additional information"

# Optional configuration:
exception:
  - "Cx01N"
  - "Hubbl3"
  - "vinnybod"
